version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    image: elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=test
      - ELASTIC_PASSWORD=test123456
    command: >
      bash -c "elasticsearch-users useradd test -p test123456 -r superuser && /bin/tini -- /usr/local/bin/docker-entrypoint.sh"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      # - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  # IOC_SCAN:
  #   image: iocs
  #   environment:
  #     - DATABASE_HOST=postgres
  #     - DATABASE_USER=postgres
  #     - DATABASE_PASSWORD=mysecretpassword
  #     - DATABASE_PORT=5432
  #     - ELASTIC_SEARCH_HOST=elasticsearch
  #     - ELASTIC_SEARCH_USER=elastic
  #     - ELASTIC_SEARCH_PASS=TESTpAss
  #   depends_on:
  #     - postgres

volumes:
  postgres_data:
  elasticsearch-data:
